In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.layers import Input, Embedding, Flatten, Dot, Dense, Concatenate
from keras.models import Model


In [2]:
user_rating = pd.read_csv('../../dataset/user_rating.csv')

In [8]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(user_rating, test_size=0.2, random_state=42)

In [13]:
# creating destination embedding path
destination_input = Input(shape=[1])
destination_embedding = Embedding(place_num+1, 5)(destination_input)
destination_flat = Flatten()(destination_embedding)

# creating user embedding path
user_input = Input(shape=[1])
user_embedding = Embedding(n_users+1, 5)(user_input)
user_flat = Flatten()(user_embedding)

# concatenate features
conc = Concatenate()([destination_flat, user_flat])

# add fully-connected-layers
x = Dense(128, activation='relu')(conc)
x = Dense(64, activation='relu')(x)
output = Dense(1)(x)

# Create model and compile it
model = Model([user_input, destination_input], output)
model.compile('adam', 'mean_squared_error')

In [15]:
history = model.fit([train.User_Id, train.Place_Id], train.Place_Ratings, epochs=20)

Epoch 1/20

229/229 [==============================] - 3s 4ms/step - loss: 3.1924
Epoch 2/20
229/229 [==============================] - 1s 3ms/step - loss: 1.8756
Epoch 3/20
229/229 [==============================] - 1s 3ms/step - loss: 1.8369
Epoch 4/20
229/229 [==============================] - 1s 3ms/step - loss: 1.8173
Epoch 5/20
229/229 [==============================] - 1s 3ms/step - loss: 1.8116
Epoch 6/20
229/229 [==============================] - 1s 3ms/step - loss: 1.8035
Epoch 7/20
229/229 [==============================] - 1s 3ms/step - loss: 1.7974
Epoch 8/20
229/229 [==============================] - 1s 3ms/step - loss: 1.7980
Epoch 9/20
229/229 [==============================] - 1s 3ms/step - loss: 1.7906
Epoch 10/20
229/229 [==============================] - 1s 4ms/step - loss: 1.7819
Epoch 11/20
229/229 [==============================] - 1s 5ms/step - loss: 1.7651
Epoch 12/20
229/229 [==============================] - 1s 3ms/step - loss: 1.7452
Epoch 13/20
229/229 [===

In [19]:
# Creating dataset for making recommendations for the first user
tourism_data = np.array(list(set(user_rating.Place_Id)))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [22]:
id_user = 5
user = np.array([id_user for i in range(len(tourism_data))])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Predict

In [23]:
predictions = model.predict([user, tourism_data])

predictions = np.array([a[0] for a in predictions])

recommended_tourism_ids = (-predictions).argsort()[:10]

recommended_tourism_ids

7/7 [==============================] - 0s 2ms/step


array([ 47, 180, 112, 131, 132, 117,  22,  19, 134,  20], dtype=int64)

In [30]:
bali_dataset = pd.read_csv('../../dataset/new_bali_dataset.csv', delimiter=';')
recommended_places = bali_dataset.loc[recommended_tourism_ids, 'place']
recommended_places

47                                    Kedungu beach Bali
180                                 Tegenungan Waterfall
112                         Bali Budaya Cultural Village
131                                     Pantai Mengening
132                                   Brahmavihara Arama
117                       Taman Werdhi Budaya Art Centre
22               Monumen Operasi Lintas Laut Jawa - Bali
19                           Santhipala Spring Waterfall
134    Lapangan Puputan Badung (I Gusti Ngurah Made A...
20                          Monumen MBO DPRI Sunda Kecil
Name: place, dtype: object